services:
  - type: web
    name: nithisha-collection
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
